language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install nose coveralls click clickclick requests
script:
  - nosetests --with-coverage --cover-package=oakkeeper
after_success:
  - coveralls
